### ISSUE TITLE
Create chat room GUI

### ISSUE THREAD

**Issue by regina-acosta** [marleyacosta/Hangman-Game-with-Chat-Room#2]
Possibly useful:

- http://usingpython.com/simple-gui-programming/
- http://ecs-network.serv.pacific.edu/past-courses/2013-fall-ecpe-177/projects/example-python3-gui/view

**Comment by nicolettecelli** [comment]
http://stackoverflow.com/questions/31727089/python-chat-box-whith-tkinter

**Comment by nicolettecelli** [comment]
http://www.rohitab.com/discuss/topic/32248-chat-clientserver/

**Comment by nicolettecelli** [comment]
https://github.com/whiteSkar/python_p2p_chat/tree/master/classes
